.PHONY: start execute

all: start

code = Kunal_Ghosh_AE_291_Assignment_4_SD.ipynb

start: 
	@echo "We are running the make file.... \n"

execute: ${code}
	@echo "We are opening the Jupyter Notebook in your default web browser.... \n"
	jupyter-notebook ${code}
